
services:
  mysql:
    image: mysql:8.0
    container_name: munmarketplace-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mun_marketplace
      MYSQL_USER: mun_user
      MYSQL_PASSWORD: mun_pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: munmarketplace-phpmyadmin
    restart: always
    platform: linux/amd64       # Important for Apple Silicon
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8081:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: munmarketplace-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
